# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db7c8aefab68df5b68bf7a6c0c7f177c11663de6f65c1cf95de29d783df0ef44a28efde2984b4f6c7961e89150383565c73e56270a757cbd285617cedcc829cd

test:
  secret_key_base: dd9cc97ad8f013a5234103950a70ad1a71cc34b03496a428d34250129eb906652a71253bda4c2e5861191f2f89080417a22f188706e8648ecad4f982db7aac68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
